### ISSUE TITLE
نحوه مشارکت

### ISSUE THREAD

**Issue by MahdiAbbasi7** [barnamenevisi/awesome-persian#4]
سلام و درود، 
امیدوارم حالتون خوب باشه.
برای مشارکت میتونیم به صورت pull request عمل کنیم ، یا صرفا منابع رو بهتون معرفی کنیم و شما خودتون قرار میدید؟

**Comment by rzashakeri** [comment]
> سلام و درود، امیدوارم حالتون خوب باشه. برای مشارکت میتونیم به صورت pull request عمل کنیم ، یا صرفا منابع رو بهتون معرفی کنیم و شما خودتون قرار میدید؟

سلام ممنونم 

هر جفتش و هر کدوم که راحت تر هستید
